save_dir: "output_linear_1000_20_ffw_encoder/"
data_dir: "../data_linear_1000/"
d_model: 128
d_ff: 1024
dropout: 0.1
N_State: 6
N_Control: 6
attn_type: "softmax"
h: 8
nu: 1000
u_model: 256
batch_size: 256
lr: 0.001
num_epoches: 2500
predict_num: 20
window_size: 150
lambda_1: 0.5
lambda_2: 1
lambda_3: 10
