save_dir: "output_linear_1000_20_MatrixWithInputs"
data_dir: "../data_linear_1000"
window_size: 150
predict_num: 20
nu: 1000
pca_dim: 4
dic_model: 20
u_model: 64
N_Control: 6
N_State: 6
Ku_size: 256
Ku_dd: 256
N_Matrix: 6
lr: 0.001
batch_size: 256
num_epochs: 2500
experiment: "MatrixWithInputs"